version: '3.0'
networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: ros:noetic
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always
    logging:
        driver: none

  ros-astra-camera:
    build:
      context: ros_astra_camera
      dockerfile: Dockerfile
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    privileged: true
    command: roslaunch astra_camera embedded_s.launch
    networks:
      - ros
    logging:
        driver: none

  ros-depth-calibration:
    image: osrf/ros:melodic-desktop-full
    depends_on:
      - ros-master
      - ros-astra-camera
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "DISPLAY=$DISPLAY"
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./camera_info:/root"
    group_add:
      - video
    privileged: true
    tty: true
    command: bash -c "rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.250 image:=/camera/ir/image camera:=/camera/ir && cd /tmp && tar -xvzf /tmp/calibrationdata.tar.gz && mv ost.yaml /root/depth_Astra_Orbbec.yaml"
    networks:
      - ros
